<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<!-- The "windows10.0.19041.0" part is CRITICAL. It unlocks the LampArray and Windows.Devices APIs -->
		<TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<!-- This allows the System Tray NotifyIcon to work -->
		<UseWindowsForms>true</UseWindowsForms>
		<!-- Fixes the Appx packaging errors -->
		<GenerateAppxPackageOnBuild>false</GenerateAppxPackageOnBuild>
		<Platforms>AnyCPU;x64</Platforms>
		<ApplicationManifest>app.manifest</ApplicationManifest>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="Images\1.png" />
	  <None Remove="Images\2.png" />
	  <None Remove="Images\desktop.ini" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="Images\1.png">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Images\2.png">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

	<!-- Your NuGet Packages -->
	<ItemGroup>
		<PackageReference Include="NAudio" Version="2.2.1" />
		<PackageReference Include="WPF-UI" Version="4.2.0" />
	</ItemGroup>

</Project>